#!/bin/sh -l
module load python3/3.6.5


date
hostname
pushd /projectnb/peaclab-cri-cooling/EDAToolDevelopment/CRI-Cooling-Tool/src/

chiplabel=$1
folder=$2
lcf_File=${folder}$3
configFile=${folder}$4
modelParamsFile=${folder}$5
pdenType=$6
pdenVal=$7
grid_dir=$8
gridFilePrefix=$9
scp_dir=${10}

echo "$chiplabel, $folder, $lcf_File, $configFile, $modelParamsFile, $pdenType, $pdenVal, $grid_dir, $gridFilePrefix, $scp_dir"


time python dummy_scc.py

#popd 
#date



